### ISSUE TITLE
Does IBM support this SDN interconnect on Openshift :0) 

### ISSUE THREAD

**Issue by mcousine** [raffaelespazzoli/openshift-sdn-encrypted-tunnel#1]
Installation: Once again, it is important to note that this solution **is not officially supported by Red Hat and is currently a personal initiative to demonstrate strategies** for supporting this type of solution.

Does IBM support it :0) Good job Raffaeles.

**Comment by raffaelespazzoli** [comment]
not sure what to do with this issue, closing for now.
