### ISSUE TITLE
Install fails when serviceType set to NodePort

### ISSUE THREAD

**Issue by chrisbsmith** [raffaelespazzoli/openshift-sdn-encrypted-tunnel#3]
```
TASK [deploy-tunnel : make sure all the ips are provisioned] *******************************************************************************************************************************************************************************************************************
FAILED - RETRYING: make sure all the ips are provisioned (2 retries left).
FAILED - RETRYING: make sure all the ips are provisioned (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 10, "changed": true, "cmd": "oc --context default/console-vpn1-deciphernow-com:8443/demo get svc -n sdn-tunnel -o custom-columns=IP:status.loadBalancer.ingress[0].ip --no-headers=true | grep -v none", "delta": "0:00:00.678261", "end": "2018-12-05 12:13:26.315949", "msg": "non-zero return code", "rc": 1, "start": "2018-12-05 12:13:25.637688", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

From the example inventory file, `serviceType` is set to `NodePort` but the above task fails even thought there is a check to execute only `when: service_type == 'LoadBalancer'  `
https://github.com/raffaelespazzoli/openshift-sdn-encrypted-tunnel/blob/f402e44984aa5c0bafd589461a707e093e1d4168/ansible/inventory/host_vars/localhost#L2

https://github.com/raffaelespazzoli/openshift-sdn-encrypted-tunnel/blob/f402e44984aa5c0bafd589461a707e093e1d4168/ansible/roles/deploy-tunnel/tasks/add-ips.yaml#L12

Changed the default to `NodePort` and the install succeeded.
https://github.com/raffaelespazzoli/openshift-sdn-encrypted-tunnel/blob/f402e44984aa5c0bafd589461a707e093e1d4168/ansible/roles/deploy-tunnel/defaults/main.yaml#L8

**Comment by raffaelespazzoli** [comment]
the example inventory is wrong is should be:
service_type: NodePort.

**Comment by raffaelespazzoli** [comment]
closed by https://github.com/raffaelespazzoli/openshift-sdn-encrypted-tunnel/commit/a830d50211f580731c3c0baa55297e44baa37868
