### ISSUE TITLE
sdn-tunnel crashes

### ISSUE THREAD

**Issue by chrisbsmith** [raffaelespazzoli/openshift-sdn-encrypted-tunnel#4]
Thanks for this walk-through.  I'm running into a few issues trying deploying the sdn-tunnels though.  They fail to run in both OpenShift clusters.  Below is the log from the Pod.  They fail into a backoff loop and attempt to restart but always fail with this error.

```
running cleanup
--
  | running unwireOVSPodInOut
  | cluster_cidr: 10.128.0.0/14 , cidr: 10.128.0.0/14 , port: 28
  | ovs-ofctl: unknown keyword priority
  | ovs-ofctl: unknown keyword priority
  | running setup
  | running setupwg
  | RTNETLINK answers: Operation not supported
```

The service-proxy is running without issue.

I am running OCP 3.11, with 1 master and 1 compute node and the same example inventory file, but with my OCP values.

**Comment by raffaelespazzoli** [comment]
I have seen a similar error when I didn't have wireguard installed.
It needs to be installed in every node.
Instructions are here:
https://github.com/raffaelespazzoli/openshift-sdn-encrypted-tunnel#install-wireguard

**Comment by chrisbsmith** [comment]
I did follow those instructions and am able run `wg` on the nodes 
```
[ec2-user@ip-10-100-67-48 ~]$ wg -v
Invalid subcommand: `-v'
Usage: wg <cmd> [<args>]
```

I do receive this message from the install
```
Non-fatal POSTIN scriptlet failure in rpm package 1:wireguard-dkms-0.0.20181119-1.el7.noarch
```

Manually running the ansible commands
```
[ec2-user@ip-192-168-89-110 ~]$ sudo yum install -y epel-release-latest-7.noarch.rpm
Loaded plugins: amazon-id, product-id, rhui-lb, search-disabled-repos, subscription-manager
Examining epel-release-latest-7.noarch.rpm: epel-release-7-11.noarch
epel-release-latest-7.noarch.rpm: does not update installed package.
Error: Nothing to do
[ec2-user@ip-192-168-89-110 ~]$ sudo yum install -y wireguard-dkms wireguard-tools
Loaded plugins: amazon-id, product-id, rhui-lb, search-disabled-repos, subscription-manager
Package 1:wireguard-dkms-0.0.20181119-1.el7.noarch already installed and latest version
Package 1:wireguard-tools-0.0.20181119-1.el7.x86_64 already installed and latest version
Nothing to do
[ec2-user@ip-192-168-89-110 ~]$
```

**Comment by chrisbsmith** [comment]
So it looks like wireguard did not get installed initially
```
[ec2-user@ip-10-100-18-126 ~]$ modprobe wireguard
modprobe: FATAL: Module wireguard not found.
```

I was eventually able to install wireguard by setting SELinux to Permissive and installing `kernel-devel-uname-r == $(uname -r)`.  After those updates, wireguard installed successfully.  However, I am receiving this error now (similar but different last line)
```

  | running cleanup
-- | --
  | running unwireOVSPodInOut
  | cluster_cidr: 10.128.0.0/14 , cidr: 10.128.0.0/14 , port: 6
  | ovs-ofctl: unknown keyword priority
  | ovs-ofctl: unknown keyword priority
  | running setup
  | running setupwg
  | RTNETLINK answers: File exists

```

**Comment by chrisbsmith** [comment]
Well, turns out it helps if your OpenShift clusters have differing pod cidr ranges.
